title: Servv AI Documentation
description: Documentation site for JustTheDocs
# Because this is a *project site*, baseurl must be your repo name (the subdirectory)
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://github.com/vijaycoderisetechnologies"

# --- THEME SETUP ---
remote_theme: "pmarsceill/just-the-docs"

# If you want to use plugins supported by GitHub Pages, include them
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  
# Optional: markdown, permalinks, etc.
markdown: kramdown
permalink: pretty

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

aux_links:
  "Servv AI on GitHub":
    - "https://github.com/coderisetechnologiesinc/servvai-event-booking"
aux_links_new_tab: true